version: '3.6'
services:
  nginx:
    image: nginx:${NGINX_VERSION:-latest}
    labels:
        com.github.jrcs.letsencrypt_nginx_proxy_companion.nginx_proxy: "true"
    container_name: ${NGINX:-nginx}
    restart: always
    depends_on:
      - wordpress 
    ports:
      - "${IP:-0.0.0.0}:${DOCKER_HTTP:-80}:80"
      - "${IP:-0.0.0.0}:${DOCKER_HTTPS:-443}:443"
    volumes:
      - ${NGINX_FILES_PATH:-./nginx}/conf.d:/etc/nginx/conf.d
      - ${NGINX_FILES_PATH:-./nginx}/vhost.d:/etc/nginx/vhost.d
      - ${NGINX_FILES_PATH:-./nginx}/html:/usr/share/nginx/html
      - ${NGINX_LOG_DIR:-./logs/nginx}:/var/log/nginx
      - ${NGINX_FILES_PATH:-./nginx}/certs:/etc/nginx/certs:ro
      - ${NGINX_FILES_PATH:-./nginx}/htpasswd:/etc/nginx/htpasswd:ro
      - ${WORDPRESS_DATA_DIR:-./wordpress}:/var/www/html
    logging:
      driver: ${NGINX_LOG_DRIVER:-json-file}
      options:
        max-size: ${NGINX_LOG_MAX_SIZE:-4m}
        max-file: ${NGINX_LOG_MAX_FILE:-10}

  nginx-gen:
    image: jwilder/docker-gen
#    command: -notify-sighup ${NGINX:-nginx} -watch -wait 5s:30s /etc/docker-gen/templates/nginx.tmpl /etc/nginx/conf.d/default.conf
    command: -notify-sighup ${NGINX:-nginx} -watch -wait 5s:30s /etc/docker-gen/templates/nginx.tmpl /etc/nginx/default.conf
    container_name: ${DOCKER_GEN:-nginx-gen}
    restart: always
    volumes:
      - ${NGINX_FILES_PATH:-./nginx}/conf.d:/etc/nginx/conf.d
      - ${NGINX_FILES_PATH:-./nginx}/vhost.d:/etc/nginx/vhost.d
      - ${NGINX_FILES_PATH:-./nginx}/html:/usr/share/nginx/html
      - ${NGINX_LOG_DIR:-./logs/nginx}:/var/log/nginx
      - ${NGINX_FILES_PATH:-./nginx}/certs:/etc/nginx/certs:ro
      - ${NGINX_FILES_PATH:-./nginx}/htpasswd:/etc/nginx/htpasswd:ro
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - ./nginx.tmpl:/etc/docker-gen/templates/nginx.tmpl:ro
      - ${WORDPRESS_DATA_DIR:-./wordpress}:/var/www/html
    logging:
      driver: ${NGINX_GEN_LOG_DRIVER:-json-file}
      options:
        max-size: ${NGINX_GEN_LOG_MAX_SIZE:-2m}
        max-file: ${NGINX_GEN_LOG_MAX_FILE:-10}

  nginx-letsencrypt:
    image: jrcs/letsencrypt-nginx-proxy-companion
    container_name: ${LETS_ENCRYPT:-nginx-letsencrypt}
    restart: always
    volumes:
      - ${NGINX_FILES_PATH:-./nginx}/conf.d:/etc/nginx/conf.d
      - ${NGINX_FILES_PATH:-./nginx}/vhost.d:/etc/nginx/vhost.d
      - ${NGINX_FILES_PATH:-./nginx}/html:/usr/share/nginx/html
      - ${NGINX_LOG_DIR:-./logs/nginx}:/var/log/nginx
      - ${NGINX_FILES_PATH:-./nginx}/certs:/etc/nginx/certs:rw
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ${WORDPRESS_DATA_DIR:-./wordpress}:/var/www/html
    environment:
      NGINX_DOCKER_GEN_CONTAINER: ${DOCKER_GEN:-nginx-gen}
      NGINX_PROXY_CONTAINER: ${NGINX:-nginx}
    logging:
      driver: ${NGINX_LETSENCRYPT_LOG_DRIVER:-json-file}
      options:
        max-size: ${NGINX_LETSENCRYPT_LOG_MAX_SIZE:-2m}
        max-file: ${NGINX_LETSENCRYPT_LOG_MAX_FILE:-10}

  mysql:
    container_name: ${CONTAINER_DB_NAME:-mysql}
    image: mariadb:${MARIADB_VERSION:-latest}
    restart: unless-stopped
    volumes:
        - ${DB_PATH:-./mysql}:/var/lib/mysql
    environment:
       MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD:-Kn0x2@@5}
       MYSQL_DATABASE: ${MYSQL_DATABASE:-sunkissedlilacs}
       MYSQL_USER: ${MYSQL_USER:-Dane}
       MYSQL_PASSWORD: ${MYSQL_PASSWORD:-Kn0x2@@5}
    restart: always

  wordpress:
     depends_on:
       - mysql
     ports:
       - 8081:80
     container_name: ${CONTAINER_WP1_NAME:-wordpress}
     image: wordpress:${WORDPRESS_VERSION:-php7.3-fpm}
     restart: unless-stopped
     volumes:
       - ${WORDPRESS_DATA_DIR:-./wordpress}:/var/www/html
       - ./uploads.ini:/usr/local/etc/php/conf.d/uploads.ini
     environment:
       WORDPRESS_DB_HOST: ${CONTAINER_DB_NAME:-mysql}
       WORDPRESS_DB_NAME: ${MYSQL_DATABASE:-sunkissedlilacs}
       WORDPRESS_DB_USER: ${MYSQL_USER:-Dane}
       WORDPRESS_DB_PASSWORD: ${MYSQL_PASSWORD:-Kn0x2@@5}
       WORDPRESS_TABLE_PREFIX: ${WORDPRESS_TABLE_PREFIX:-wp_}
       VIRTUAL_HOST: ${DOMAINS:-sunkissedlilacs.com,www.sunkissedlilacs.com}
#      VIRTUAL_PROTO: https
#       VIRTUAL_PORT: 8081
       LETSENCRYPT_HOST: ${DOMAINS:-sunkissedlilacs.com,www.sunkissedlilacs.com}
       LETSENCRYPT_EMAIL: ${LETSENCRYPT_EMAIL:-info@sunkissedlilacs.com} 
       WPFPM_WP_REDIS_HOST: redis
       WPFPM_RT_WP_NGINX_HELPER_CACHE_PATH: "/tmp/cache"
       WP_PLUGINS: "nginx-helper redis-cache mailgun my-other-plugin" 

  phpmyadmin:
     depends_on:
       - mysql
     image: phpmyadmin/phpmyadmin
     restart: always
     ports:
       - 8088:80
     environment:
       PMA_HOST: mysql
       MYSQL_ROOT_PASSWORD: Kn0x2@@5

  redis:
     image: redis:alpine
     container_name: redis
     restart: always
     ports:
      - "6379:6379"


networks:
  default:
    external:
      name: ${NETWORK}